# Generated by Django 4.1.4 on 2023-01-03 22:21

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('schedule', wagtail.fields.StreamField([('upper_heading', wagtail.blocks.CharBlock()), ('lower_heading', wagtail.blocks.CharBlock()), ('day', wagtail.blocks.ChoiceBlock(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')])), ('worktime_from', wagtail.blocks.TimeBlock()), ('worktime_to', wagtail.blocks.TimeBlock()), ('address_upper', wagtail.blocks.CharBlock()), ('address_lower', wagtail.blocks.CharBlock()), ('short_message', wagtail.blocks.CharBlock()), ('phone', wagtail.blocks.CharBlock())], blank=True, use_json_field=None)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
