# Generated by Django 4.1.4 on 2023-01-09 00:11

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('contact_info', wagtail.fields.StreamField([('info', wagtail.blocks.StreamBlock([('headers', wagtail.blocks.StructBlock([('upper_heading', wagtail.blocks.CharBlock()), ('lower_heading', wagtail.blocks.CharBlock())], icon='title')), ('schedule', wagtail.blocks.StreamBlock([('string', wagtail.blocks.StructBlock([('day', wagtail.blocks.ChoiceBlock(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')])), ('worktime_from', wagtail.blocks.TimeBlock(required=False)), ('worktime_to', wagtail.blocks.TimeBlock(required=False))], icon='list-ul'))], block_counts={'string': {'max_num': 7, 'min_num': 7}}, icon='date')), ('address', wagtail.blocks.StructBlock([('address_upper', wagtail.blocks.CharBlock(max_length=250)), ('address_lower', wagtail.blocks.CharBlock(max_length=250, required=False))], icon='home')), ('contacts', wagtail.blocks.StructBlock([('short_message', wagtail.blocks.CharBlock(max_length=250, required=False)), ('phone', wagtail.blocks.CharBlock(max_length=15, required=False)), ('email', wagtail.blocks.CharBlock(max_length=250, required=False))], icon='mail'))], block_counts={'address': {'max_num': 1}, 'contacts': {'max_num': 1}, 'headers': {'max_num': 1}, 'schedule': {'max_num': 1}}, icon='clipboard-list'))], blank=True, use_json_field=None)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
