# Generated by Django 4.1.4 on 2023-01-03 18:44

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='intro',
            field=wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock()), ('upper_heading', wagtail.blocks.CharBlock(form_classname='upper_heading')), ('lower_heading', wagtail.blocks.CharBlock(form_classname='lower_heading')), ('text', wagtail.blocks.RichTextBlock()), ('button_text', wagtail.blocks.CharBlock()), ('button_url', wagtail.blocks.URLBlock())], blank=True, use_json_field=None),
        ),
    ]
