# Generated by Django 4.1.4 on 2023-01-03 19:31

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='message',
            field=wagtail.fields.StreamField([('upper_heading', wagtail.blocks.CharBlock()), ('lower_heading', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.RichTextBlock())], blank=True, use_json_field=None),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='intro',
            field=wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock()), ('upper_heading', wagtail.blocks.CharBlock()), ('lower_heading', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.RichTextBlock()), ('button_text', wagtail.blocks.CharBlock()), ('button_url', wagtail.blocks.URLBlock())], blank=True, use_json_field=None),
        ),
    ]
